id: P005625
initial_creation_type: ocr
source_metadata:
  id: bdr:W28838
  title: བོ་དོང་པཎ་ཆེན་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    3c82ca816ed74a39b4d5efb7e965a3fb:
      image_group_id: I4710
      title: ''
      volume_number: 1
      total_pages: 457
      base_file: v001.txt
